### PR TITLE
fix: use signing key

### PR DESCRIPTION
**Pull request by stevennevins**

### CODE REVIEW

**Review by wesfloyd — COMMENTED** [review]
Wes CI/CD bot 🤖 

forget tests pass


image

image


Manual e2e test fails at `npm run start:traffic`

image


image

**Comment by stevennevins** [comment]
@wesfloyd Fixed the offchain code. I had to put in a quick fix for the threshold stake check since hello world wasn't depositing tokens into a strategy (ie operator has 0 weight).  I was already addressing this in my other PR so i just set the required threshold stake to 0 for now

**Comment by wesfloyd** [comment]
Looks good - ready to merge

image
image

**Review by wesfloyd — APPROVED** [review]
lgtm - rdy to merge

**Pull request merged**
